### ISSUE TITLE
Авторизация через U/P не работает для YandexMusicClient

### ISSUE THREAD

**Issue by skuill** [K1llMan/Yandex.Music.Api#7]
**В чем проблема:**
При попытке авторизоваться через метод `public bool Authorize(string login, string password)` класса `Yandex.Music.Client.YandexMusicClient` возвращается ошибка:
```
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Yandex.Music.Api.Requests.YRequest`1.GetWebResponseAsync()
   at Yandex.Music.Api.Requests.YRequest`1.GetWebResponseAsync()
   at Yandex.Music.Api.Requests.YRequest`1.GetResponseAsync()
   at Yandex.Music.Api.API.YUserAPI.AuthPassport(AuthStorage storage, String login, String password)
   at Yandex.Music.Api.API.YUserAPI.AuthorizeAsync(AuthStorage storage, String login, String password)
   at Yandex.Music.Api.API.YUserAPI.Authorize(AuthStorage storage, String login, String password)
   at Yandex.Music.Client.YandexMusicClient.Authorize(String login, String password)
```

**В чем причина:**
Как я понимаю начиная [с некоторого момента](https://yandex-music.readthedocs.io/en/main/#id4) осталась возможность авторизоваться только по токену. 
Метод авторизации по токену отрабатывает как нужно.
Для получения токена по U/P нашел такую информацию из телеграмм группы (использовал 1 метод из списка):
```
Своё OAuth приложение создать нельзя. Единственный вариант это использовать приложения официальных клиентов Яндекс.Музыка. 

- Самый простой способ получения токена: https://github.com/MarshalX/yandex-music-api/discussions/513#discussioncomment-2729781
- Сайт для получения токена который работает не со всеми аккаунтами: https://music-yandex-bot.ru/
- Скрипт получения токена для изучения. В этом чате с ним не помогают: https://github.com/AlexxIT/YandexStation/blob/master/custom_components/yandex_station/core/yandex_session.py
```

**Что предлагается**
Может кто-то проверить, действительно ли перестала работать авторизация по U/P ?
Если так, то предлагаю либо удалить метод из класса, либо пометить его как устаревший.

**Comment by martin211** [comment]
Fixed at Pull Reuest #11

**Comment by K1llMan** [comment]
Добавлены разные варианты авторизации.
